'use client';
import './globals.css';
import { QueryClient, QueryClientProvider } from 'react-query';
import { store } from '../redux/store';
import { Provider } from 'react-redux';

const queryClient = new QueryClient();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Include necessary head tags */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <QueryClientProvider client={queryClient}>
          <Provider store={store}>
            {children}
          </Provider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
